### ISSUE TITLE
AdjustDesignators2: not centered, text size wrong, changes font

### ISSUE THREAD

**Issue by Xeyow** [Altium-Designer-addons/scripts-libraries#112] opened 2023-05-25 10:23 UTC
I tried running this script on AD 23.5.1 and it looks like it's easier to manually place _.Designators_ from Assembly layers, in the center of the components, than using this script.

[Manual](https://www.photobox.co.uk/my/photo?album_id=7026368757&photo_id=505502409707)

[Script](https://www.photobox.co.uk/my/photo?album_id=7026368757&photo_id=505502419892)

Settings used for the script: 

Use Stroke Fonts: **unchecked**
Layer Options: Consider Mech Layer Primitives: **checked**
Designators to Include: Modify Designator on Mechanical Layers: **checked**

I assumed this script would center the designators, and increase/decrease their font size so they fit in the assembly perimeter of the component. For components that are rotated 45* degrees, the designator is either horizontal, or vertical. Any way to fix this?

Thanks!

**Comment by justinmassiot** [comment] 2023-05-31 13:39
Hello @Xeyow ,
Thanks for your feedback. Though I'm unable to access the picture you wanted to share... they're probably not publicly accessible.

> I assumed this script would center the designators, and increase/decrease their font size so they fit in the assembly perimeter of the component. For components that are rotated 45* degrees, the designator is either horizontal, or vertical.

You're right, this is what it should do.

I will use the script by the end of last week for my internal needs. I'll see what works what doesn't, and check if I can fix what's broken.
Stay tuned.

**Comment by RnDMonkey** [comment] 2023-06-07 23:56
@Xeyow if you already have the .Designator strings in your components and you just want to position and scale them, you might see if [SelectAssyDesignators Script](https://github.com/Altium-Designer-addons/scripts-libraries/tree/master/Scripts%20-%20PCB/SelectAssyDesignators) works for you in the meantime. It's not a comprehensive as AdjustDesignators2 in terms of determining the area of the part (it only uses pads in component, you can't select a specific layer to use for bounds), but it doesn't change the font style.

**Comment by BrettLMiller** [comment] 2023-06-08 00:20
Clarify:
AdjustDesignators2 does NOT add the .Designator special string to any layer.
There is a partner script that can be used to add them. But Altium now has a great tool to add them.

Problem Statement:
The OPs post title does not really match the content & there are no screenshots. Hard to understand the problem.

Altium Churn:
The latest Altium has once again fiddled about with IPCB_Text primitives so there could be an improvement made to AdjustDesignators2.
But we need to discover the undocumented features.

**Comment by Xeyow** [comment] 2023-06-09 11:28
Hello @BrettLMiller,

Please use the following photos:

Capture1 = Manual
![Capture1](https://github.com/Altium-Designer-addons/scripts-libraries/assets/11709779/9c73fd19-21d1-4baf-800e-4e6d72b8b50b)

Capture3 = Script
![Capture3](https://github.com/Altium-Designer-addons/scripts-libraries/assets/11709779/e46cf328-cdbe-4041-967a-ecf6580a52fa)

**Comment by Xeyow** [comment] 2023-06-09 11:43
@RnDMonkey, thanks for suggesting [SelectAssyDesignators Script](https://github.com/Altium-Designer-addons/scripts-libraries/tree/master/Scripts%20-%20PCB/SelectAssyDesignators) - it kinda does what I wanted, but it has some missing features:

- I need to manually select the .designators string
- After doing this, when selecting: ResetDesignatorPositions... it perfectly places all the designators in the center of the component (and as you said, without resizing them)... but the orientation could be fixed:

![Capture1](https://github.com/Altium-Designer-addons/scripts-libraries/assets/11709779/c41d15c7-0b27-4c44-97b3-618a99654eb8)

R44 has a rotation of 270, and R42 has a rotation of 90... Although it rotates the string correctly, it would be nice if it would maintain only 2 directions (that can be selected by the user, or by default): from left to right and from below to above. In this case, the designator of R44 should've been rotated another 180 to accommodate the requirement.

Other than that, if it would do this and resize the string based on the contour (from the assembly layer)... this script would be the real deal! For now it helps me on around 50% of what I need to do, which is more than the 0% i had before using it 👍

**Comment by RnDMonkey** [comment] 2023-06-10 01:08
Hi @Xeyow there are several procedures in the script, please see the documentation. You can use the *SelectDesignators* function with components selected, and it will switch to their .Designator strings. Likewise *SelectComponents* will do the reverse. *SelectBoth* will take any combination of the two and select both of them, which you could follow up with one of the commands.

As for the 90° rotation, did you try the *ResetDesignatorPositionsNorm* function? It should do what you want.

**Comment by RnDMonkey** [comment] 2023-06-10 01:13
Regarding using a contour on the assembly layer, from your example picture I see a challenge there: how should it treat Q15 and Q17? I would guess you want to use the large box around the text, without the boxes representing the pins, but this is programmatically challenging to automate.

**Comment by Xeyow** [comment] 2023-06-10 07:17
Hello @RnDMonkey, I will try using the norm function first thing on Monday and come back to you with an answer.

Regarding the assembly of the the transistors, I imagine it's pretty hard to determine the body contour, as you have multiple boxes. We usually, (and Altium also recommends this) place a box (with no other information) on the Guard layer. This one is a little bit bigger than the assembly, but it's a box. Maybe the script could ask the user which layer to select, so it can search for a box on that specific layer.

In any case, if the norm function does what I want (having only 2 directions for the designators)... it would be a HUGE success. I do not mind reviewing the designators and fixing a couple of strings. Thanks!

**Comment by BrettLMiller** [comment] 2023-06-10 23:47
@Xeyow  Sizing text inside a tight box that is rotated from cardinal axis is more tricky but doable (rotate copy of box to cardinal).
Later Altium does support bounding boxes at any angle but I've not found it is exposed in scripting API.

Contouring all primitives (inc. the text) is possible just slow in scripting. I am doing this in AdjustDes2.2.
But I going to park that method & going to try using spatial iterator in search of free space. I think this is faster than calculations in script.
The problem is the scripting API  spatial iterator does not support rotated bounding rectangle.
And a duplicate dummy footprint will be missing any primitives that do not belong to group primitive. 

But not sure if this will happen, I use Draftsman &/or just use a simple private script that has defined text height for each footprint pattern.

For me, a more useful script is one that checks designator text is closer to parent than all other designator text & reports warnings & errors in the Messages panel for navigation.

**Comment by Xeyow** [comment] 2023-06-19 09:36
@RnDMonkey, thanks for suggesting _ResetDesignatorPositionsNorm_, it does exactly what I wanted. Speaking of multiple assembly rectangles... that transistor has a wrong assembly drawing, it should've been only one rectangle, the body itself (without the pins). In this case, you could search for the rectangle and resize the text based on the size of the rectangle.

**Comment by RnDMonkey** [comment] 2023-06-20 05:47
As @BrettLMiller pointed out, things get tricky when components are rotated, and it's even harder when there are multiple regions. There are many possible methods depending on how the user's footprint, but there are so many corner cases I can think of that I'm not eager to even get started.

**Comment by Xeyow** [comment] 2023-06-20 06:00
Hello @RnDMonkey, I understand, and I appreciate your support and involvement. There would be one last thing: when using the _SelectDesignators_, why do I need to select the components first?

It is easier to right click on a designator, click find similar, and select SAME for text and layer...

It would be great if the _SelectDesignators_ would do exactly what it says: select all designators. Same thing goes for _SelectComponents_ and _SelectBoth_

What do you think?

**Comment by RnDMonkey** [comment] 2023-06-21 09:40
I always intended for the commands to be run on a selection rather than the
whole board. I figure it is only one quick query to select all components,
if that's what you want.

**Comment by justinmassiot** [comment] 2023-07-18 20:19
Hello all,
@BrettLMiller, can you please open a Pull Request with your version "2.2", or tell use where to access the source code? I think I'm going to make some changes but starting from the "newer" version would be best.
Thanks!

**Comment by BrettLMiller** [comment] 2023-07-18 21:11
My latest is not online & is very different to public copy as it was based on my never released V3..
I did recently make some improvements to my private copy (still works in AD17). But I still have not resolved some issues with bottom side rotated footprints/text. I believe it is solvable with some effort.
But that effort comes at a cost.

**Comment by RnDMonkey** [comment] 2023-07-25 18:06
@Xeyow , if you're still using SelectAssyDesignators script, note that I've renamed it to AssemblyTextPrep, added a bunch of functionality, and a GUI! See [AssemblyTextPrep in the repo](https://github.com/Altium-Designer-addons/scripts-libraries/tree/master/Scripts%20-%20PCB/AssemblyTextPrep)

**Comment by justinmassiot** [comment] 2023-07-27 09:46
Hello @Xeyow.
@RnDMonkey have merged the corrections brought by @BrettLMiller in PR #148. This means the newly available AdjustDesignators2 script is our best known version to date.

If your original issue is not resolved, please feel free to reopen this ticket with your updated feedbacks.

**Closed by justinmassiot** 2023-07-27 09:46 UTC
